version: '3'
services:
  scrape:
    build: ./scrape
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    enivronment:
      - MONGO_INITDB_ROOT_USERNAME=user
	    - MONGO_INITDB_ROOT_PASSWORD=passwd

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=passwd
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
